alias ls='ls -al --color=auto'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias tarnow='tar -acf '
alias untar='tar -zxvf '

alias ga='git add'
alias gst='git status'
alias gco='git checkout'
alias gcm='git commit -m'
alias gbr='git branch'
alias gdf='git diff'
alias glgp='git log -p'
alias glg='git log'
alias gps='git push'


