alias ls='ls -al -F --color=auto --show-control-chars'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias tarnow='tar -acf '
alias untar='tar -zxvf '